trigger:
  branches:
    include:
      - main  # Replace with the name of your main branch

pr:
  branches:
    exclude:
      - '*'

pool:
  vmImage: 'ubuntu-latest'

steps:
  - script: |
      ssh-keyscan github.com >> ~/.ssh/known_hosts
      git clone https://github.com/seunsodimu/dawsonpicks.git /home/dawsonreports/www/kpi
      cd /home/dawsonreports/www/kpi
      git pull origin main
    displayName: 'Update Website from GitHub'
